services: 
  - type: web
    name: flask-api
    env: python
    rootDir: back-end
    buildComand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - fromDotEnv: true